# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selefra < Formula
  desc "selefra exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://selefra.io/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/selefra/selefra/releases/download/v0.1.0/selefra_darwin_arm64.zip"
      sha256 "0e8f9e8be29bb41b05f9bafe4a47e44671997882f22159835aa72b37327e8fd2"

      def install
        bin.install "selefra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selefra/selefra/releases/download/v0.1.0/selefra_darwin_amd64.zip"
      sha256 "5f49c980101bc4c7b774187ca95cdb88b5ec68253d78488c613fcf78ca748541"

      def install
        bin.install "selefra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selefra/selefra/releases/download/v0.1.0/selefra_linux_arm64.tar.gz"
      sha256 "47a0321aa3627def91a4714d3a8b2056e3f8f681b830161359aeea73aba1531e"

      def install
        bin.install "selefra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selefra/selefra/releases/download/v0.1.0/selefra_linux_amd64.tar.gz"
      sha256 "e4aaad586c70f2739370d37bf09d31e59e8134834956cafb4ee80b290587c6fe"

      def install
        bin.install "selefra"
      end
    end
  end
end
