# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Selefra < Formula
  desc "Selefra - Infrastructure as Code for Infrastructure Analysis."
  homepage "https://selefra.io/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/selefra/selefra/releases/download/v0.0.1/selefra_darwin_arm64.zip"
      sha256 "4c5093c3b3171a1c24f4388956f72ce969a04d53e22ad747ea54184f9e98f5f7"

      def install
        bin.install "selefra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selefra/selefra/releases/download/v0.0.1/selefra_darwin_amd64.zip"
      sha256 "34cffd1fca8883bd8196139fd55b8fc3185f6922a9d5301fa221db7f63ae0fb2"

      def install
        bin.install "selefra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/selefra/selefra/releases/download/v0.0.1/selefra_linux_amd64.tar.gz"
      sha256 "7661b38586b0e199a6f95024af837db6a9df14a0576931abfb0c8212331007ce"

      def install
        bin.install "selefra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selefra/selefra/releases/download/v0.0.1/selefra_linux_arm64.tar.gz"
      sha256 "4d12f907c9d5af1e44ccb7c7ab19a65b8e9265bd16bcfd8a23f865f6b316ad84"

      def install
        bin.install "selefra"
      end
    end
  end
end
